#!/usr/bin/env python
#_*_coding:utf-8_*_

num_rr=[1,2,3,4,5,6,7,8,9]
for i in num_rr:
    p=[]
    for n in num_rr:
        if i>=n :
            m=i*n
            j='%s*%s=%s'%(i,n,m)
            p.append(j)
    z=",".join(p)
    print z
    
#!/usr/bin/env python
#_*_coding:utf-8_*_
num_rr=[1,2,3,4,5,6,7,8,9]

for i in num_rr:
    temp=''
    for j in num_rr:
        if j<=i:
            temp+='%s*%s=%s '%(i,j,i*j)
    print temp
