#!/usr/bin/env python
#_*_coding:utf-8_*_
#求两个数组共同值（去重）

arr1=[1,2,3,4,2,12,3,14,3,2,12,3,14,21,2,2,3,4111,22,3333,4]
arr2=[2,1,3,2,43,234,454,452,234,14,21,14]
new_arr=[]
for i in arr1:
    if i not in new_arr:
        new_arr.append(i)
        for j in arr2:
            if j not in new_arr:
                new_arr.append(j)
print  new_arr


两个数组找共同值
arr1=[1,2,3,4,2,12,3,14,3,2,12,3,14,21,2,2,3,4111,22,3333,4]
arr2=[2,1,3,2,43,234,454,452,234,14,21,14]
new_arr=[]
for i in arr1:
    if i in arr2 and i not in new_arr:
        new_arr.append(i)
print new_arr 
