#!/usr/bin/env python
#_*_coding:utf-8_*_
#用户名密码用：分割，让用户输入用户名和密码，判断是否能登陆
arr=['user:pwd','user1:pwd1','user2:pwd2']
while True:
    ra_user=raw_input('请输入你的用户名：')
    ra_pwd=raw_input('请输入你的密码：')
    a=ra_user+':'+ra_pwd
    #把两字符串拼接在一起，中间加：
    #   a=':'.join([ra_user,ra_pwd]) 此方法也可以
    print a
    if a in arr:
        print '登陆成功'
        break
    else:
        print '用户名或密码错误'
        
-------------------------------------------        
请输入你的用户名：user
请输入你的密码：pwd
user:pwd
登陆成功
------------------------------------------

 先判断用户名是否正缺，然后再判断密码
arr=['user:pwd','user1:pwd1','user2:pwd2']
#先判断用户名，成功后在判断密码
user_list=[]
pwd_list=[]
for i in arr:           #挨个循环列表里的字符串
    temp=i.split(':')    #把每字符串以‘：’切割成 list
    print temp
    user_list.append(temp[0]) #把列表里第0个放到一个新的列表
    #
    pwd_list.append(temp[1])  #把列表里第1个放到另一个新的列表
while True:
    raw_user=raw_input('输入用户名：')
    if raw_user in user_list:
        raw_pwd=raw_input('输入密码')
        if raw_pwd == pwd_list[user_list.index(raw_user)]:  #user列表里和pwd列表里位置一一对应，user表里第几个索引，对应pwd里德索引值
            print 'success'
            break
        else:
            print 'not passwd'
            pass
    else:
        print 'user not exists'
print user_list
print pwd_list

-----------------------------------------------
输入用户名：user
输入密码ii
not passwd
输入用户名：user
输入密码paww
not passwd
输入用户名：user
输入密码pwd
success
['user', 'user1', 'user2']
['pwd', 'pwd1', 'pwd2']
---------------------------------------------------
